spring:
  application:
    name: seniorway
    deploy: ${deploy.status}

  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:mysql://seniorway.cjks2yqsihxa.ap-northeast-2.rds.amazonaws.com:3306/seniorway?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: seniorway

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            redirect-uri: ${kakao.redirect-uri}
            authorization-grant-type: authorization_code
            client-authentication-method: post
            client-name: Kakao
            scope:
              - name
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
      timeout: ${redis.timeout}
      ssl:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  address: 0.0.0.0

jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}
  refreshExpiration: ${jwt.refreshExpiration}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

KTO:
  KTO_TOUR_INFO_API_KEY: ${KTO.KTO_TOUR_INFO_API_KEY}
  KTO_TOUR_VISITOR_PREDICT_API_KEY: ${KTO.KTO_TOUR_VISITOR_PREDICT_API_KEY}

app:
  frontend:
    base-url: "http://localhost:5173"